In [1]:
# This model uses logistic Regression

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import pickle

In [3]:
data = pd.read_csv("Crop_Recommendation.csv")

In [4]:
data.head()

Nitrogen  Phosphorus  Potassium  Temperature   Humidity  pH_Value  \
0        90          42         43    20.879744  82.002744  6.502985   
1        85          58         41    21.770462  80.319644  7.038096   
2        60          55         44    23.004459  82.320763  7.840207   
3        74          35         40    26.491096  80.158363  6.980401   
4        78          42         42    20.130175  81.604873  7.628473   

     Rainfall  Crop  
0  202.935536  Rice  
1  226.655537  Rice  
2  263.964248  Rice  
3  242.864034  Rice  
4  262.717340  Rice

In [5]:
data.describe()

Nitrogen   Phosphorus    Potassium  Temperature     Humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

          pH_Value     Rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Nitrogen     2200 non-null   int64  
 1   Phosphorus   2200 non-null   int64  
 2   Potassium    2200 non-null   int64  
 3   Temperature  2200 non-null   float64
 4   Humidity     2200 non-null   float64
 5   pH_Value     2200 non-null   float64
 6   Rainfall     2200 non-null   float64
 7   Crop         2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [7]:
data.head()

Nitrogen  Phosphorus  Potassium  Temperature   Humidity  pH_Value  \
0        90          42         43    20.879744  82.002744  6.502985   
1        85          58         41    21.770462  80.319644  7.038096   
2        60          55         44    23.004459  82.320763  7.840207   
3        74          35         40    26.491096  80.158363  6.980401   
4        78          42         42    20.130175  81.604873  7.628473   

     Rainfall  Crop  
0  202.935536  Rice  
1  226.655537  Rice  
2  263.964248  Rice  
3  242.864034  Rice  
4  262.717340  Rice

In [8]:
data.tail()

Nitrogen  Phosphorus  Potassium  Temperature   Humidity  pH_Value  \
2195       107          34         32    26.774637  66.413269  6.780064   
2196        99          15         27    27.417112  56.636362  6.086922   
2197       118          33         30    24.131797  67.225123  6.362608   
2198       117          32         34    26.272418  52.127394  6.758793   
2199       104          18         30    23.603016  60.396475  6.779833   

        Rainfall    Crop  
2195  177.774507  Coffee  
2196  127.924610  Coffee  
2197  173.322839  Coffee  
2198  127.175293  Coffee  
2199  140.937041  Coffee

In [9]:
# identifying all the crops
data["Crop"].unique()

array(['Rice', 'Maize', 'ChickPea', 'KidneyBeans', 'PigeonPeas',
       'MothBeans', 'MungBean', 'Blackgram', 'Lentil', 'Pomegranate',
       'Banana', 'Mango', 'Grapes', 'Watermelon', 'Muskmelon', 'Apple',
       'Orange', 'Papaya', 'Coconut', 'Cotton', 'Jute', 'Coffee'],
      dtype=object)

In [10]:
labels_encode = {
    'Rice':1, 
    'Maize':2, 
    'ChickPea':3, 
    'KidneyBeans':4, 
    'PigeonPeas':5,
    'MothBeans':6, 
    'MungBean':7, 
    'Blackgram':8, 
    'Lentil':9, 
    'Pomegranate':10,
    'Banana':11, 
    'Mango':12, 
    'Grapes':13, 
    'Watermelon':14, 
    'Muskmelon':15, 
    'Apple':16,
    'Orange':17, 
    'Papaya':18, 
    'Coconut':19, 
    'Cotton':20, 
    'Jute':21, 
    'Coffee':22
}

In [11]:
data["Crop"]=data["Crop"].map(labels_encode)

In [12]:
data.head()

Nitrogen  Phosphorus  Potassium  Temperature   Humidity  pH_Value  \
0        90          42         43    20.879744  82.002744  6.502985   
1        85          58         41    21.770462  80.319644  7.038096   
2        60          55         44    23.004459  82.320763  7.840207   
3        74          35         40    26.491096  80.158363  6.980401   
4        78          42         42    20.130175  81.604873  7.628473   

     Rainfall  Crop  
0  202.935536     1  
1  226.655537     1  
2  263.964248     1  
3  242.864034     1  
4  262.717340     1

In [13]:
input = data.drop("Crop",axis=1)
output = data["Crop"]
x_train,x_test,y_train,y_test = train_test_split(input,output,test_size=0.2,random_state=1)

In [14]:
len(x_train)

1760

In [15]:
len(x_test)

440

In [16]:
len(y_train)

1760

In [17]:
len(y_test)

440

In [18]:
model_one = LogisticRegression()

In [19]:
model_one.fit(x_train,y_train)

C:\Users\Emmanuel\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
predict = model_one.predict(x_test)

In [21]:
predict

array([13, 15,  4, 15, 21, 14,  4, 17, 21,  5, 10, 21, 22, 12,  6, 11, 11,
       19, 11, 17,  9, 16, 10, 18, 15, 11, 13, 19, 20, 14,  2,  2, 15, 16,
        6, 20, 12,  8,  9, 17,  5, 13, 17, 18, 19, 10, 18, 22,  3, 21,  3,
       22,  9, 10, 22,  7, 14, 14, 20, 12,  8,  7, 10, 11, 22, 15,  3, 13,
       16, 21, 13, 12, 17,  2,  1, 14, 14,  2, 20, 12,  3, 11, 16, 17, 20,
        8, 20, 12,  6, 10, 21,  5, 13, 14,  7,  7,  4, 20, 13,  7, 11, 21,
       18,  6, 19, 18, 10, 11, 20,  2,  7, 16, 10,  3, 15,  9,  8, 12,  2,
       22,  8, 21, 15, 20,  4,  3,  4,  6, 14,  7,  1,  9, 17, 16,  4,  3,
       20, 19,  3,  7,  9,  8, 22,  5, 15, 10, 18,  9,  6, 14,  7, 19,  9,
        1, 12,  7,  2,  8, 20, 21,  1, 21, 13,  6, 14,  5,  7, 16,  6,  3,
        5, 19,  5,  9, 13, 21,  1,  1, 20, 13, 20, 13, 20, 15,  8, 10, 22,
       18, 13, 11, 14, 17, 11, 16, 15,  7,  9, 13, 21,  1, 19,  8, 15,  7,
        5,  1,  2,  9, 11, 10, 14,  1, 21,  4, 15,  2, 21,  9, 22, 22,  6,
       21,  4, 20, 20, 15

In [22]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           1       0.79      0.85      0.81        13
           2       0.94      0.85      0.89        20
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        19
           6       0.96      0.96      0.96        24
           7       1.00      0.96      0.98        24
           8       1.00      1.00      1.00        22
           9       0.90      1.00      0.95        18
          10       1.00      1.00      1.00        23
          11       1.00      1.00      1.00        18
          12       1.00      1.00      1.00        17
          13       1.00      1.00      1.00        29
          14       1.00      1.00      1.00        19
          15       1.00      1.00      1.00        26
          16       1.00      1.00      1.00        22
          17       1.00      1.00      1.00        15
          18       0.92    

In [23]:
confusion_matrix(y_test,predict)

array([[11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  2,  0],
       [ 0, 17,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  2,  0,  1],
       [ 0,  0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 23,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 23,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 23,  0,  0,

In [24]:
accuracy_score(y_test,predict)

0.9704545454545455

In [25]:
print(model_one.coef_)

[[ 0.19922442 -0.25886482 -0.21933167 -0.52861444 -0.10711114 -0.14764596
   0.39719202]
 [ 0.44985247 -0.01064751 -0.3052118  -0.01116259 -0.09217455  0.04883461
   0.11317305]
 [-0.00481441  0.27765037  0.60898993 -0.0354264  -0.54812724  0.02822442
  -0.02503962]
 [-0.18566349  0.69925062 -0.04459042 -0.01342485 -0.81993534  0.06671397
   0.19114493]
 [-0.22091641  0.38539983 -0.51756799  0.11966461 -0.01985405 -0.06264517
   0.22875806]
 [-0.25091832  0.19713958 -0.10826317  0.82162529 -0.03563315  0.3433609
  -0.00545394]
 [-0.27914542  0.02095598 -0.42387474 -0.03671965  0.60547227 -0.02766345
  -0.04791811]
 [-0.15513277  0.4437325  -0.44857149  0.26732185  0.05615083 -0.07198412
   0.05389826]
 [-0.22789097  0.57591385 -0.30986152 -0.1945189   0.26962272  0.08985676
  -0.16222532]
 [-0.32156169 -0.40152145  0.33972608 -0.1629262   0.43651667  0.01901623
   0.09050404]
 [ 0.41022128  0.14400355  0.22888876 -0.14763553 -0.30227966 -0.0927527
   0.05606409]
 [-0.30269328 -0.154010

In [26]:
model_one.intercept_

array([-0.01297834,  0.02242808,  0.00234044,  0.01282025, -0.00458595,
        0.0564576 , -0.00396711, -0.02190128,  0.00623475,  0.00250703,
       -0.01195834,  0.03003941, -0.0037115 ,  0.00035651,  0.00076202,
       -0.00669432,  0.00339408, -0.05175515, -0.00293282, -0.01620278,
       -0.00313312,  0.00248054])

In [30]:
#saving the model using pickle

with open("model_one.pkl","wb") as f:
    pickle.dump(model_one,f)

In [28]:
#loading the model 
with open("model_one.py","rb") as f:
    model = pickle.load(f)

In [29]:
model_one.predict([[50,50,50,50,50,50,50]])

C:\Users\Emmanuel\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([6], dtype=int64)